;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_create_new_element
	.import		_mainloop
	.import		_readdir
	.import		_ksprint_hex
	.export		_action
	.export		_emain

; ---------------------------------------------------------------
; void __near__ action (char *name)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_action: near

.segment	"CODE"

	jsr     pushax
	ldx     #$78
	lda     #$90
	jsr     _ksprint_hex
	lda     #$FF
	sta     $800A
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ emain (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_emain: near

.segment	"CODE"

	jsr     decsp2
	lda     #$01
	jsr     pusha
	jmp     L0004
L0002:	lda     #$08
	jsr     pusha
	lda     #$01
	sec
	tay
	sbc     (sp),y
	jsr     pusha
	ldy     #$06
	jsr     pushwysp
	lda     #$01
	jsr     pusha
	lda     #<(_action)
	ldx     #>(_action)
	jsr     _create_new_element
	ldx     #$00
	txa
	tay
	sta     (sp),y
L0004:	jsr     _readdir
	ldy     #$01
	jsr     staxysp
	cpx     #$00
	bne     L0002
	cmp     #$00
	bne     L0002
	jsr     _mainloop
	jmp     incsp3

.endproc

