;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_strcmp
	.import		_memset
	.import		_krectangle
	.import		_kprint
	.import		_kclear
	.import		_init_flash
	.import		_kill_flash
	.export		_flashing
	.export		_input_buf
	.export		_input_buf_write_ptr
	.export		_input_buf_read_ptr
	.export		_shell

.segment	"DATA"

_input_buf:
	.word	$7E00
_input_buf_write_ptr:
	.word	$7DFF
_input_buf_read_ptr:
	.byte	$00

.segment	"RODATA"

S0002:
	.byte	$77,$6F,$72,$6C,$64,$0A,$00
S0003:
	.byte	$63,$6C,$65,$61,$72,$00
S0004:
	.byte	$66,$6C,$61,$73,$68,$00
S0001:
	.byte	$68,$65,$6C,$6C,$6F,$00
S0005:
	.byte	$6B,$69,$6C,$6C,$00

; ---------------------------------------------------------------
; void __near__ flashing (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_flashing: near

.segment	"CODE"

	lda     #$02
	jsr     pusha
	jsr     decsp4
	lda     $8005
	ldy     #$03
	sta     (sp),y
	lda     $8006
	dey
	sta     (sp),y
L0002:	ldy     #$04
	lda     (sp),y
	clc
	adc     #$01
	and     #$07
	sta     (sp),y
	dey
	lda     (sp),y
	jsr     pusha
	lda     #$20
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     pusha
	lda     #$20
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     _krectangle
	lda     #$C0
	ldy     #$01
	jmp     L0010
L000D:	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
L000A:	ldy     #$00
	lda     (sp),y
	bne     L000D
	iny
	clc
	tya
	adc     (sp),y
L0010:	sta     (sp),y
	tya
	dey
	sta     (sp),y
	iny
	lda     (sp),y
	bne     L000A
	jmp     L0002

.endproc

; ---------------------------------------------------------------
; void __near__ shell (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_shell: near

.segment	"CODE"

	ldy     #$19
	jsr     subysp
	lda     #$00
	jsr     pusha
	jsr     decsp2
	ldy     #$01
L0002:	lda     M0001,y
	sta     (sp),y
	dey
	bpl     L0002
	lda     #$03
	jsr     leaa0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$17
L001C:	sta     (ptr1),y
	dey
	bpl     L001C
	lda     ptr1
	ldx     ptr1+1
	jsr     _kclear
	jmp     L000A
L0006:	lda     _input_buf
	ldx     _input_buf+1
	ldy     _input_buf_read_ptr
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	ldy     #$1B
	sta     (sp),y
	ldy     #$00
	sta     (sp),y
	lda     sp
	ldx     sp+1
	jsr     _kprint
	inc     _input_buf_read_ptr
	ldy     #$1B
	lda     (sp),y
	cmp     #$08
	jeq     L0017
	cmp     #$0D
	jne     L0019
	lda     #$03
	jsr     leaa0sp
	jsr     pushax
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     _strcmp
	cpx     #$00
	bne     L000C
	cmp     #$00
	bne     L000C
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     _kprint
	jmp     L0015
L000C:	lda     #$03
	jsr     leaa0sp
	jsr     pushax
	lda     #<(S0003)
	ldx     #>(S0003)
	jsr     _strcmp
	cpx     #$00
	bne     L000F
	cmp     #$00
	bne     L000F
	jsr     _kclear
	jmp     L0015
L000F:	lda     #$03
	jsr     leaa0sp
	jsr     pushax
	lda     #<(S0004)
	ldx     #>(S0004)
	jsr     _strcmp
	cpx     #$00
	bne     L0012
	cmp     #$00
	bne     L0012
	jsr     _init_flash
	jmp     L0015
L0012:	lda     #$03
	jsr     leaa0sp
	jsr     pushax
	lda     #<(S0005)
	ldx     #>(S0005)
	jsr     _strcmp
	cpx     #$00
	bne     L0015
	cmp     #$00
	bne     L0015
	jsr     _kill_flash
L0015:	lda     #$03
	jsr     leaa0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	ldy     #$17
L001D:	sta     (ptr1),y
	dey
	bpl     L001D
	lda     #$00
	ldy     #$02
	jmp     L001E
L0017:	lda     #$03
	jsr     leaa0sp
	ldy     #$02
	sta     ptr1
	stx     ptr1+1
	lda     (sp),y
	tay
	lda     #$00
	sta     (ptr1),y
	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$01
	jmp     L001E
L0019:	lda     #$03
	jsr     leaa0sp
	sta     ptr1
	stx     ptr1+1
	lda     (sp),y
	pha
	ldy     #$02
	lda     (sp),y
	tay
	pla
	sta     (ptr1),y
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
L001E:	sta     (sp),y
L000A:	lda     _input_buf_write_ptr+1
	sta     ptr1+1
	lda     _input_buf_write_ptr
	sta     ptr1
	ldy     #$00
	lda     (ptr1),y
	cmp     _input_buf_read_ptr
	jne     L0006
	jmp     L000A

.segment	"RODATA"

M0001:
	.byte	$00
	.byte	$00

.endproc

