;
; File generated by cc65 v 2.19 - N/A
;
	.fopt		compiler,"cc65 v 2.19 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_hline
	.export		_krectangle

; ---------------------------------------------------------------
; void __near__ hline (char x, char w, char y, char color)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hline: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (sp),y
	asl     a
	asl     a
	asl     a
	asl     a
	sta     ptr1
	lda     (sp),y
	ora     ptr1
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	lsr     a
	jsr     pusha
	lda     #$00
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	lsr     a
	sta     $8001
	lda     (sp),y
	and     #$01
	cmp     #$01
	bne     L0002
	tay
	clc
	lda     #$80
	adc     (sp),y
	sta     (sp),y
L0002:	ldy     #$06
	lda     (sp),y
	and     #$01
	cmp     #$01
	bne     L0004
	tay
	lda     (sp),y
	sta     $8000
	lda     $8002
	and     #$F0
	sta     ptr1
	ldy     #$03
	lda     (sp),y
	ora     ptr1
	sta     $8002
	ldy     #$01
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	tya
	dey
L000D:	sta     (sp),y
L0004:	ldx     #$00
	lda     (sp,x)
	jsr     pusha0
	ldy     #$07
	lda     (sp),y
	jsr     decax1
	jsr     tosicmp
	bpl     L0007
	ldy     #$01
	lda     (sp),y
	sta     $8000
	iny
	lda     (sp),y
	sta     $8002
	dey
	clc
	tya
	adc     (sp),y
	sta     (sp),y
	dey
	clc
	lda     #$02
	adc     (sp),y
	jmp     L000D
L0007:	ldy     #$06
	lda     (sp),y
	and     #$01
	cmp     #$01
	jsr     booleq
	sta     ptr1
	dey
	lda     (sp),y
	and     #$01
	cmp     #$01
	jsr     booleq
	eor     ptr1
	beq     L000A
	ldy     #$01
	lda     (sp),y
	sta     $8000
	lda     $8002
	and     #$0F
	sta     ptr1
	ldy     #$03
	lda     (sp),y
	asl     a
	asl     a
	asl     a
	asl     a
	ora     ptr1
	sta     $8002
L000A:	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; void __near__ krectangle (char x, char w, char y, char h, char color)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_krectangle: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	ldy     #$03
	lda     (sp),y
	ldy     #$00
L0007:	sta     (sp),y
	lda     (sp),y
	jsr     pusha0
	ldy     #$04
	lda     (sp),y
	clc
	iny
	adc     (sp),y
	bcc     L0006
	inx
L0006:	jsr     tosicmp
	bpl     L0003
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     _hline
	ldy     #$00
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0007
L0003:	jmp     incsp6

.endproc

